import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import { Inter, Roboto, Oswald } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import { ThemeProvider } from '../context/ThemeContext'
import AuthProvider from '@/components/authProvider/AuthProvider'


const inter = Inter({ subsets: ['latin'] })
const oswald = Oswald({ subsets: ['latin'] })

export const metadata = {
  title: 'NextBlog',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <ThemeProvider>
          <AuthProvider>
        <div className='container'>
        <Navbar />
        {children}
        <Footer />
        </div>
        </AuthProvider>
        </ThemeProvider>

        </body>
    </html>
  )
}
